//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_ProgrammingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
